image: tonipes/sfml-docker:0.3

before_script:
  - git submodule update --init --recursive

stages:
  - build
  - make
  - test
  - cleanup

variables:
  CC: /usr/bin/clang
  CXX: /usr/bin/clang++

# cache:
#   untracked: true
#   paths:
#     - build

build:
  stage: build
  script:
    - ./build.sh

make:
  stage: make
  script:
    - ./build.sh make

unit_test:
  stage: test
  script:
    - ./build.sh test

run_test:
  stage: test
  script:
    - ./build.sh testrun

cleanup_build:
  stage: cleanup
  script:
    - ./build.sh clean
